### ISSUE TITLE
Convert JSON output to VTT for the transcripts we think used the best-performing settings

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/whisper-pilot#18]
Based on filtering the [results spreadsheet](https://docs.google.com/spreadsheets/d/1gniXFO5kix5TcmQYrvMYJN17fm9hKzNVCYqeYiS4yDc/edit?gid=1079071348#gid=1079071348&fvid=408299301) to these settings
```
{'model_name': 'large', 'beam_size': 5, 'patience': 1.0, 'condition_on_previous_text': False, 'best_of': 5}
```
it looks like the transcripts to transform are:

```
bb158br2509-whisper-019
bg405cn7261-whisper-067
bw689yg2740-whisper-163
fh290wd1772-whisper-211
gj097zq7635-whisper-259
gk220dt2833-whisper-307
gn213vd3845-whisper-355
kp010zv7055-whisper-403
qf378nj5000-whisper-451
tc482fh1865-whisper-499
```

Since I'm not doing an exact side-by-side comparison with another transcript but am primarily looking for hallucinations, the default conversion to VTT should be fine.

**Comment by edsu** [comment]
I've zipped them up in a file attached here: [vtts.zip](https://github.com/user-attachments/files/18044692/vtts.zip). Let me know if something looks amiss.

If you are curious, like @alundgard said on the call earlier, there's a Whisper function for generating the various outputs from the JSON file:

```python
from whisper.utils import get_writer

json_file = 'gj097zq7635-whisper-259.json'

result = json.load(open(json_file))

writer = get_writer(output_format="all", output_dir='vtts')
writer(result, json_file, {})
```

**Comment by jmartin-sul** [comment]
@andrewjbtw thinks this is done, closing, comparison complete
